### ISSUE TITLE
nodenv shell <version> doesn't work

### ISSUE THREAD

**Issue by wfarr** [wfarr/nodenv#1]
It just seems to write back out to the console rather than eval properly. I think I'm missing something kind of obvious on this one.

/cc @jbarnette

**Comment by cronopio** [comment]
Fixed on fba3573579931245277b4bc316c199b546e26845

**Comment by shellbj** [comment]
This is still an issue.  This has to do with the way rbenv rebinds itself as an alias to either eval the -sh commands or  execute the actual script.

https://github.com/sstephenson/rbenv/blob/master/libexec/rbenv-init#L94
```
commands=(`rbenv-commands --sh`)
rbenv() {
  local command
  command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${commands[*]})
    eval "\`rbenv "sh-\$command" "\$@"\`";;
  *)
    command rbenv "\$command" "\$@";;
  esac
}
```
